[package]
name = "sfo-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
lazy_static = "1.4.0"
governor = "0.5.1"
serde = "1.0.160"
serde_json = "1.0.96"
log = "0.4.17"
jsonwebtoken = "8.3.0"
surf = { version = '2.3.2', default-features = false, features = ['h1-client-rustls'] }
http-client = "6.5.3"
rustls = {version = "0.18", features = ["dangerous_configuration"]}
webpki = "0.21.0"
webpki-roots = "0.22.6"
chrono = "0.4.24"
