[package]
name = "sfo-http"
version = "0.4.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/wugren/sfo-http.git"
description = "private http library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = { version = "0.16.0", optional = true }
lazy_static = "1.4.0"
governor = "0.5.1"
serde = "1.0.160"
serde_json = "1.0.96"
log = "0.4.17"
jsonwebtoken = "8.3.0"
reqwest = {version = "0.11.17", default-features = false, features = ["rustls-tls", "json"]}
chrono = "0.4.24"
json = "0.12.4"
sfo-result = "0.2"
actix-web = { version = "4", optional = true}
async-trait = "0.1.80"
futures-util = "0.3"
serde_qs = "0.13"

[features]
